### ISSUE TITLE
Purpose can be more focused.

### ISSUE THREAD

**Issue by Charles-Hoot** [sumana-reddy/GDP-1-project#3]
Purposes are why's, not what's.
Example: What - build a team.  Why - form bonds/meet other students.  You can give both, but don't leave out the why.

**Comment by Vikas2004** [comment]
Thanks for the info Dr.Hoot. The part which was missing(why?) is now added to the purpose. Hopefully, I addressed this issue. We are always ready to hear the reviews and make possible changes to meet them.
