### ISSUE TITLE
The ERD doesn't look consistent

### ISSUE THREAD

**Issue by Charles-Hoot** [sumana-reddy/GDP-1-project#5]
I am not a database expert, but use of id's is not consistent.  Not sure if all fields are needed.  E.g. Do you need a date for invitation rejected, or date left the team.  Do you need an explicit association for captain.

I am sure there is more that your DB expert (Dr Case) can address.

**Comment by Vikas2004** [comment]
I think we do need the ids we mentioned here as it would make the associative entities without any identifier. However, we will work on the ER diagram after consulting Dr.Case if any changes are needed to the ER we charted down.
