### ISSUE TITLE
Cost estimate is confusing

### ISSUE THREAD

**Issue by Charles-Hoot** [sumana-reddy/GDP-1-project#6]
There are hours per week determined, but it doesn't look like they transferred correctly to the cost estimate.  There are lines in the cost estimate with hours but no billing.

I always wanted the hourly billing rate up front.

Without better numbers, I hesitate to look closer, but my sense is that you have not included enough time for implementation and testing.

**Comment by Vikas2004** [comment]
The Cost estimate was a bit clumsy previously and now has been rectified. The testing is named in our table as the monitoring and controlling. We assumed the testing will be conducted in this structure and we are still not sure if we need another structure for the testing phase. Please do help us with this.
