### ISSUE TITLE
Are there other challenges?

### ISSUE THREAD

**Issue by Charles-Hoot** [sumana-reddy/GDP-1-project#7]
I view social distancing as a feature of this app as long as we don't have to stand next to each other to get the points.

The big challenges I see (aside from GPS) are:  Specifying a location, handling data, and creating/managing teams.

**Comment by Vikas2004** [comment]
The challenges mentioned here are overlooked by us. But now these are also added to the section of challenges and we may even face new issues and challenges as we go along but at this point, these are the main things that are being considered.
