### ISSUE TITLE
User Stories/Acceptance Criteria need work

### ISSUE THREAD

**Issue by Charles-Hoot** [sumana-reddy/GDP-1-project#9]
A user story is related to a role in the app.  Acceptance Criteria need to measurable objects.

Example:  A Data Developer is not role in the app.
Example: A given task for the development of the ERD has been finished is not specific.

**Comment by Vikas2004** [comment]
The above issue is assigned to @sumanthreddy1233 and we will regroup together and discuss about how to improve this and sumanth will take up this task.
